#!/usr/bin/env bash
# Auto-generated by setup_local_certs.sh
# Starts the RWE MCP server with HTTPS enabled.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export SSL_CERTFILE="$SCRIPT_DIR/certs/localhost.pem"
export SSL_KEYFILE="$SCRIPT_DIR/certs/localhost-key.pem"
export MCP_HOST="${MCP_HOST:-127.0.0.1}"
export MCP_PORT="${MCP_PORT:-9090}"

echo "Starting RWE MCP Server with HTTPS …"
echo "  Endpoint : https://$MCP_HOST:$MCP_PORT/mcp"
echo "  Cert     : $SSL_CERTFILE"
echo ""

cd "$SCRIPT_DIR"
python server.py
